version: "3.9"

services:
  webapp:
    build: ./webapp
    container_name: webapp
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run --host=0.0.0.0 --port=5000
