version: '3.8'

services:
  webapp:
    build: ./webapp
    container_name: container-webserver
    image: beginner090902/container-webserver-webapp:latest
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts  # Stellt meinskript.py zur Verfügung
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Berlin
      - FLASK_APP=app.py  # Wichtig: Sag Flask welche App Datei
      - FLASK_ENV=production
      - PYTHONPATH=/scripts  # Füge zum Python Path hinzu
      - PASSWORD=${PASSWORD}
      - Name_of_your_container=${Name_of_your_container}
      - Auto_Stop=${Auto_Stop}
      - Auto_Stop_Time=${Auto_Stop_Time}
    command: flask run --host=0.0.0.0 --port=5000